/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProfileVerifyEmailRouteImport } from './routes/profile/verify-email'
import { Route as ProfileResetPasswordRouteImport } from './routes/profile/reset-password'
import { Route as LoginCreateAccountRouteImport } from './routes/login/create-account'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ModpackUsernameModpackIdIndexRouteImport } from './routes/modpack/$username.$modpackId/index'
import { Route as SuggestionUsernameModpackIdSuggestionIdViewRouteImport } from './routes/suggestion/$username.$modpackId.$suggestionId/view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileVerifyEmailRoute = ProfileVerifyEmailRouteImport.update({
  id: '/profile/verify-email',
  path: '/profile/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileResetPasswordRoute = ProfileResetPasswordRouteImport.update({
  id: '/profile/reset-password',
  path: '/profile/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCreateAccountRoute = LoginCreateAccountRouteImport.update({
  id: '/login/create-account',
  path: '/login/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpackUsernameModpackIdIndexRoute =
  ModpackUsernameModpackIdIndexRouteImport.update({
    id: '/modpack/$username/$modpackId/',
    path: '/modpack/$username/$modpackId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuggestionUsernameModpackIdSuggestionIdViewRoute =
  SuggestionUsernameModpackIdSuggestionIdViewRouteImport.update({
    id: '/suggestion/$username/$modpackId/$suggestionId/view',
    path: '/suggestion/$username/$modpackId/$suggestionId/view',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/create-account': typeof LoginCreateAccountRoute
  '/profile/reset-password': typeof ProfileResetPasswordRoute
  '/profile/verify-email': typeof ProfileVerifyEmailRoute
  '/login': typeof LoginIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/modpack/$username/$modpackId': typeof ModpackUsernameModpackIdIndexRoute
  '/suggestion/$username/$modpackId/$suggestionId/view': typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/create-account': typeof LoginCreateAccountRoute
  '/profile/reset-password': typeof ProfileResetPasswordRoute
  '/profile/verify-email': typeof ProfileVerifyEmailRoute
  '/login': typeof LoginIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/modpack/$username/$modpackId': typeof ModpackUsernameModpackIdIndexRoute
  '/suggestion/$username/$modpackId/$suggestionId/view': typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/create-account': typeof LoginCreateAccountRoute
  '/profile/reset-password': typeof ProfileResetPasswordRoute
  '/profile/verify-email': typeof ProfileVerifyEmailRoute
  '/login/': typeof LoginIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/modpack/$username/$modpackId/': typeof ModpackUsernameModpackIdIndexRoute
  '/suggestion/$username/$modpackId/$suggestionId/view': typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/create-account'
    | '/profile/reset-password'
    | '/profile/verify-email'
    | '/login'
    | '/profile/$username'
    | '/modpack/$username/$modpackId'
    | '/suggestion/$username/$modpackId/$suggestionId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/create-account'
    | '/profile/reset-password'
    | '/profile/verify-email'
    | '/login'
    | '/profile/$username'
    | '/modpack/$username/$modpackId'
    | '/suggestion/$username/$modpackId/$suggestionId/view'
  id:
    | '__root__'
    | '/'
    | '/login/create-account'
    | '/profile/reset-password'
    | '/profile/verify-email'
    | '/login/'
    | '/profile/$username/'
    | '/modpack/$username/$modpackId/'
    | '/suggestion/$username/$modpackId/$suggestionId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginCreateAccountRoute: typeof LoginCreateAccountRoute
  ProfileResetPasswordRoute: typeof ProfileResetPasswordRoute
  ProfileVerifyEmailRoute: typeof ProfileVerifyEmailRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ModpackUsernameModpackIdIndexRoute: typeof ModpackUsernameModpackIdIndexRoute
  SuggestionUsernameModpackIdSuggestionIdViewRoute: typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/verify-email': {
      id: '/profile/verify-email'
      path: '/profile/verify-email'
      fullPath: '/profile/verify-email'
      preLoaderRoute: typeof ProfileVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/reset-password': {
      id: '/profile/reset-password'
      path: '/profile/reset-password'
      fullPath: '/profile/reset-password'
      preLoaderRoute: typeof ProfileResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/create-account': {
      id: '/login/create-account'
      path: '/login/create-account'
      fullPath: '/login/create-account'
      preLoaderRoute: typeof LoginCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpack/$username/$modpackId/': {
      id: '/modpack/$username/$modpackId/'
      path: '/modpack/$username/$modpackId'
      fullPath: '/modpack/$username/$modpackId'
      preLoaderRoute: typeof ModpackUsernameModpackIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestion/$username/$modpackId/$suggestionId/view': {
      id: '/suggestion/$username/$modpackId/$suggestionId/view'
      path: '/suggestion/$username/$modpackId/$suggestionId/view'
      fullPath: '/suggestion/$username/$modpackId/$suggestionId/view'
      preLoaderRoute: typeof SuggestionUsernameModpackIdSuggestionIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginCreateAccountRoute: LoginCreateAccountRoute,
  ProfileResetPasswordRoute: ProfileResetPasswordRoute,
  ProfileVerifyEmailRoute: ProfileVerifyEmailRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ModpackUsernameModpackIdIndexRoute: ModpackUsernameModpackIdIndexRoute,
  SuggestionUsernameModpackIdSuggestionIdViewRoute:
    SuggestionUsernameModpackIdSuggestionIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
