/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ModpackUsernameModpackIdIndexRouteImport } from './routes/modpack/$username.$modpackId/index'
import { Route as ModpackUsernameModpackIdSuggestionsRouteImport } from './routes/modpack/$username.$modpackId/suggestions'
import { Route as SuggestionUsernameModpackIdSuggestionIdViewRouteImport } from './routes/suggestion/$username.$modpackId.$suggestionId/view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpackUsernameModpackIdIndexRoute =
  ModpackUsernameModpackIdIndexRouteImport.update({
    id: '/modpack/$username/$modpackId/',
    path: '/modpack/$username/$modpackId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModpackUsernameModpackIdSuggestionsRoute =
  ModpackUsernameModpackIdSuggestionsRouteImport.update({
    id: '/modpack/$username/$modpackId/suggestions',
    path: '/modpack/$username/$modpackId/suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuggestionUsernameModpackIdSuggestionIdViewRoute =
  SuggestionUsernameModpackIdSuggestionIdViewRouteImport.update({
    id: '/suggestion/$username/$modpackId/$suggestionId/view',
    path: '/suggestion/$username/$modpackId/$suggestionId/view',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/modpack/$username/$modpackId/suggestions': typeof ModpackUsernameModpackIdSuggestionsRoute
  '/modpack/$username/$modpackId': typeof ModpackUsernameModpackIdIndexRoute
  '/suggestion/$username/$modpackId/$suggestionId/view': typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/modpack/$username/$modpackId/suggestions': typeof ModpackUsernameModpackIdSuggestionsRoute
  '/modpack/$username/$modpackId': typeof ModpackUsernameModpackIdIndexRoute
  '/suggestion/$username/$modpackId/$suggestionId/view': typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/modpack/$username/$modpackId/suggestions': typeof ModpackUsernameModpackIdSuggestionsRoute
  '/modpack/$username/$modpackId/': typeof ModpackUsernameModpackIdIndexRoute
  '/suggestion/$username/$modpackId/$suggestionId/view': typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile/$username'
    | '/modpack/$username/$modpackId/suggestions'
    | '/modpack/$username/$modpackId'
    | '/suggestion/$username/$modpackId/$suggestionId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile/$username'
    | '/modpack/$username/$modpackId/suggestions'
    | '/modpack/$username/$modpackId'
    | '/suggestion/$username/$modpackId/$suggestionId/view'
  id:
    | '__root__'
    | '/'
    | '/login/'
    | '/profile/$username/'
    | '/modpack/$username/$modpackId/suggestions'
    | '/modpack/$username/$modpackId/'
    | '/suggestion/$username/$modpackId/$suggestionId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ModpackUsernameModpackIdSuggestionsRoute: typeof ModpackUsernameModpackIdSuggestionsRoute
  ModpackUsernameModpackIdIndexRoute: typeof ModpackUsernameModpackIdIndexRoute
  SuggestionUsernameModpackIdSuggestionIdViewRoute: typeof SuggestionUsernameModpackIdSuggestionIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpack/$username/$modpackId/': {
      id: '/modpack/$username/$modpackId/'
      path: '/modpack/$username/$modpackId'
      fullPath: '/modpack/$username/$modpackId'
      preLoaderRoute: typeof ModpackUsernameModpackIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpack/$username/$modpackId/suggestions': {
      id: '/modpack/$username/$modpackId/suggestions'
      path: '/modpack/$username/$modpackId/suggestions'
      fullPath: '/modpack/$username/$modpackId/suggestions'
      preLoaderRoute: typeof ModpackUsernameModpackIdSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestion/$username/$modpackId/$suggestionId/view': {
      id: '/suggestion/$username/$modpackId/$suggestionId/view'
      path: '/suggestion/$username/$modpackId/$suggestionId/view'
      fullPath: '/suggestion/$username/$modpackId/$suggestionId/view'
      preLoaderRoute: typeof SuggestionUsernameModpackIdSuggestionIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ModpackUsernameModpackIdSuggestionsRoute:
    ModpackUsernameModpackIdSuggestionsRoute,
  ModpackUsernameModpackIdIndexRoute: ModpackUsernameModpackIdIndexRoute,
  SuggestionUsernameModpackIdSuggestionIdViewRoute:
    SuggestionUsernameModpackIdSuggestionIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
